version: '3.4'

services:
  dashboard_client:
    build: .
    image: "${REGISTRY_NAME}devclubiitd/dashboard_client:0.1"
    ports:
      - ${PORT}:80
    healthcheck:
      test: ["CMD", "curl", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: "unless-stopped" 
    networks:
      - "internal"
      - "reverseproxy"
    env_file:
      - ./.env
    environment:
      - VIRTUAL_HOST

networks:
  reverseproxy:
    external:
      name: "reverseproxy"
  internal:
